name: testsnfiles

on:
  schedule:
    - cron:  '*/14 */2 * * *'
    - cron:  '3/14 1/2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Show Time and Get The IP Address
        run: |
          date
          dig +short myip.opendns.com @resolver1.opendns.com
        
      - name: get required files
        run: |
          wget https://somenote.ir/wp-content/uploads/2021/09/2015-Ford-Mustang-Apollo-Edition-4K-UHD-Wallpaper.jpg -nv --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/360-Forged-Cadillac-CTS-V-Side-View-4K-UHD-Wallpaper.jpg -nv --no-check-certificate
          sleep 4
          wget https://somenote.ir/wp-content/uploads/2021/09/planet_omega-wallpaper-3840x2160-1.jpg -nv --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/captured.mp4 -nv --no-check-certificate
          sleep 5
          wget https://somenote.ir/wp-content/uploads/2021/09/beautiful_city_night-wallpaper-5120x2880-1.jpg -nv --no-check-certificate
          sleep 8
          wget https://somenote.ir/wp-content/uploads/2021/09/2015-Dodge-Viper-SRT-GTS-Three-Quarter-Rear-View-HD-Wallpaper.jpg -nv --no-check-certificate
          sleep 1
          wget https://somenote.ir/wp-content/uploads/2021/09/fog_wave-wallpaper-7680x4320-1.jpg -nv --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/ICONA-Vulcano-4K-UHD-Wallpaper.jpg -nv --no-check-certificate
          sleep 3
          wget https://somenote.ir/wp-content/uploads/2021/09/Audi-A5-4K-UHD-Wallpaper.jpg -nv --no-check-certificate
          sleep 5
          wget https://somenote.ir/wp-content/uploads/2021/09/Nature.mp3 -nv --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/Amuse-TT-Nissan-370Z-Side-View-2K-HD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 1
          wget https://somenote.ir/wp-content/uploads/2021/09/Black-Ford-Raptor-4K-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 9
          wget https://somenote.ir/wp-content/uploads/2021/09/beautiful_singapore_reflection-wallpaper-5120x2880-1.jpg -nv  --no-check-certificate
          sleep 3
          wget https://somenote.ir/wp-content/uploads/2021/09/ICONA-Vulcano-Three-Quarter-Rear-View-4K-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 4
          wget https://somenote.ir/wp-content/uploads/2021/09/magic_3-wallpaper-3840x2160-1.jpg -nv  --no-check-certificate
          sleep 7
          wget https://somenote.ir/wp-content/uploads/2021/09/Best-Koenigsegg-Agera-RS-Wallpaper.jpg -nv  --no-check-certificate
          sleep 5
          wget https://somenote.ir/wp-content/uploads/2021/09/2018-Ford-Mustang-V8-GT-4K-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 6
          wget https://somenote.ir/wp-content/uploads/2021/09/2017-F-150-Ford-Raptor-Race-Truck-4K-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/beautiful_england_nature_countryside_scenery-wallpaper-5120x2880-1.jpg -nv  --no-check-certificate
          sleep 3
          wget https://somenote.ir/wp-content/uploads/2021/09/howto.mp4 -nv  --no-check-certificate
          sleep 8
          wget https://somenote.ir/wp-content/uploads/2021/09/2015-Subaru-WRX-STI-Engine-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 2
          wget https://somenote.ir/wp-content/uploads/2021/09/Mitsubishi-Concept-XR-PHEV-HD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 3
          wget https://somenote.ir/wp-content/uploads/2021/09/Porsche-GT2-4K-UHD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 1
          wget https://somenote.ir/wp-content/uploads/2021/09/Rocket-Bunny-Nissan-GTR-Spoiler-2K-HD-Wallpaper.jpg -nv  --no-check-certificate
          sleep 4
          wget https://somenote.ir/wp-content/uploads/2021/09/sun_rays_through_the_forest_trees_road-wallpaper-2560x1440-1.jpg -nv  --no-check-certificate
          sleep 6
          wget https://somenote.ir/wp-content/uploads/2021/09/Two-Rockford-Fosgate-12-inch-Punch-Subwoofers-in-the-Trunk-4K-UHD-Wallpaper-scaled.jpg -nv  --no-check-certificate
          sleep 3
          wget https://somenote.ir/wp-content/uploads/2021/09/world.topo_.200407.3x5400x2700.png -nv  --no-check-certificate
          
      - name: Remove Dependencies
        run: |
          rm *
